from connio.rest import Client
from connio.rest.api.v3.account.propertyy import PropertyInstance
from connio.rest.api.v3.account.method import MethodInstance
from readwrite_methods import *
from L200 import *
from utility_methods import *
from set_methods import *
from readwrite_methods import *
from query_methods import *
def wire(client, name='LogikaL200', friendly="Logika L200 Controller", base="ModbusGateway"):
    # Create Logika L200 profile
    compressor = client.account.deviceprofiles.create(name=name, 
                                                  friendly_name=friendly,
                                                  base_profile=base,
                                                  description='Logika L200 controller',
                                                  tags=['logika', 'L200'],
                                                  device_class='controller',
                                                  product_name='L200',
                                                  vendor_name='Logika'
                                                )

    #------ Add base profile properties
    
    client.account.properties(compressor.id).create(name='tagValue', data_type='string', access_type='protected', publish_type='never')

    client.account.properties(compressor.id).create(name='icon', data_type='string', access_type='public', publish_type='never')
    client.account.properties(compressor.id).create(name='cfgSerialNumber', data_type='string', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='cfgLogikaModel', data_type='string', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='cfgLogikaFwVersion', data_type='string', access_type='protected', publish_type='never')    
    client.account.properties(compressor.id).create(name='cfgLevel1Pwd', data_type='string', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='activeAlarms', data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='activeAlarmsNonAck', data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='controllerState', data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='compressorState', data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='blockingAlarm', data_type='string', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='relayOutputs', data_type='string', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name='digitalInputs', data_type='string', access_type='protected', publish_type='never')
    
    client.account.properties(compressor.id).create(name="IOBoardFwVersion", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="TotalEnergyConsumption", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="AirProduced", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="AmbientTemperature", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="InternalVoltageVcc", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="InternalVoltageVL", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="ResidualCompressorCapacity", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="ExcessCompressorCapacity", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CurrentStopPressure", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CurrentStartPressure", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CurrentTotalPower", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="AverageAirDelivery", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CurrentTotalAirDelivery", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsConfigured", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsSlave", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsSetToMaintenance", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsAvailable", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsSelected", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="CompressorsOn", data_type='object', access_type='protected', publish_type='never')

    client.account.properties(compressor.id).create(name="WPx", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="WTx", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="Vx", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="Sx", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="Rx", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="T01", data_type='object', access_type='protected', publish_type='never')
    #Slave Properties
    client.account.properties(compressor.id).create(name="SlaveFwVersions", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveControllerStates", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveRelativeSpeeds", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveControllerTypes", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveSelenoidDelays", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveAirFlows", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveNominalPowers", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveUnloadPowers", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlavePriorityInS0s", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlavePriorityInS1s", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlavePriorityInS2s", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlavePriorityInS3s", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveUnloadTimes", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveSafetyTimes", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveStartsHours", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveAnalogInputs", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveExcludedForMaints", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveEnableMaintenance", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveChangeAirFilter", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveChangeOilFilter", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveChangeSeperatorFilters", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveChangeOil", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveCheckCompressor", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveBearingLubrication", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveNumberOfTotalCompressorHours", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveNumberOfLoadCompressorHours", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveMaintCounters", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveMaintenanceLogs", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="SlaveMaintenanceCostLists", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="M0xs", data_type='object', access_type='protected', publish_type='never')
    client.account.properties(compressor.id).create(name="C0xs", data_type='object', access_type='protected', publish_type='never')
    #Clock Timer Properties
    client.account.properties(compressor.id).create(name="ClockTimers", data_type='object', access_type='protected', publish_type='never')

    #------ Add profile methods
    accessLevel2 = 'private'

    client.account.methods(compressor.id).create(name='fetchAlarmList', method_impl= MethodInstance.MethodImplementation(fetchAlarmList_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchReadRequest', method_impl= MethodInstance.MethodImplementation(fetchReadRequest_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchWriteRequest', method_impl= MethodInstance.MethodImplementation(fetchWriteRequest_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchModbusSettings', method_impl= MethodInstance.MethodImplementation(fetchModbusSettings_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchControllerStates', method_impl= MethodInstance.MethodImplementation(fetchControllerStates_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchSlaveControllerStates', method_impl= MethodInstance.MethodImplementation(fetchSlaveControllerStates_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchCompressorStates', method_impl= MethodInstance.MethodImplementation(fetchCompressorStates_body()), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='fetchCompressorStateTypes', method_impl= MethodInstance.MethodImplementation(fetchCompressorStateTypes_body()), access_type=accessLevel2)
    
    accessLevel3 = 'private'
    # Controller specific SET methods (private)
    client.account.methods(compressor.id).create(name='setIOBoardFwVersion', method_impl= MethodInstance.MethodImplementation(setIOBoardFwVersion_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setAmbientTemperature', method_impl= MethodInstance.MethodImplementation(setAmbientTemperature_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setInternalVoltageVcc', method_impl= MethodInstance.MethodImplementation(setInternalVoltageVcc_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setInternalVoltageVL', method_impl= MethodInstance.MethodImplementation(setInternalVoltageVL_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setResidualCompressorCapacity', method_impl= MethodInstance.MethodImplementation(setResidualCompressorCapacity_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setExcessCompressorCapacity', method_impl= MethodInstance.MethodImplementation(setExcessCompressorCapacity_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCurrentStopPressure', method_impl= MethodInstance.MethodImplementation(setCurrentStopPressure_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCurrentStartPressure', method_impl= MethodInstance.MethodImplementation(setCurrentStartPressure_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCurrentTotalPower', method_impl= MethodInstance.MethodImplementation(setCurrentTotalPower_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setAverageAirDelivery', method_impl= MethodInstance.MethodImplementation(setAverageAirDelivery_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCurrentTotalAirDelivery', method_impl= MethodInstance.MethodImplementation(setCurrentTotalAirDelivery_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsConfigured', method_impl= MethodInstance.MethodImplementation(setCompressorsConfigured_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsSlave', method_impl= MethodInstance.MethodImplementation(setCompressorsSlave_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsSetToMaintenance', method_impl= MethodInstance.MethodImplementation(setCompressorsSetToMaintenance_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsAvailable', method_impl= MethodInstance.MethodImplementation(setCompressorsAvailable_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsSelected', method_impl= MethodInstance.MethodImplementation(setCompressorsSelected_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setCompressorsOn', method_impl= MethodInstance.MethodImplementation(setCompressorsOn_body()), access_type=accessLevel3)


    client.account.methods(compressor.id).create(name='setTotalEnergyConsumption', method_impl= MethodInstance.MethodImplementation(setTotalEnergyConsumption_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setAirProduced', method_impl= MethodInstance.MethodImplementation(setAirProduced_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setR02', method_impl= MethodInstance.MethodImplementation(setR02_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setV01', method_impl= MethodInstance.MethodImplementation(setV01_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setWPx', method_impl= MethodInstance.MethodImplementation(setWPx_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setWTx', method_impl= MethodInstance.MethodImplementation(setWTx_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setV04', method_impl= MethodInstance.MethodImplementation(setV04_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setV02_V03', method_impl= MethodInstance.MethodImplementation(setV02_V03_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setV07', method_impl= MethodInstance.MethodImplementation(setV07_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS11', method_impl= MethodInstance.MethodImplementation(setS11_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setT01', method_impl= MethodInstance.MethodImplementation(setT01_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS14', method_impl= MethodInstance.MethodImplementation(setS14_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setR01', method_impl= MethodInstance.MethodImplementation(setR01_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS00_S01_S02', method_impl= MethodInstance.MethodImplementation(setS00_S01_S02_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS09_S10', method_impl= MethodInstance.MethodImplementation(setS09_S10_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS06', method_impl= MethodInstance.MethodImplementation(setS06_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS05', method_impl= MethodInstance.MethodImplementation(setS05_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS07_S08', method_impl= MethodInstance.MethodImplementation(setS07_S08_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS12_S13', method_impl= MethodInstance.MethodImplementation(setS12_S13_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS17', method_impl= MethodInstance.MethodImplementation(setS17_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS16', method_impl= MethodInstance.MethodImplementation(setS16_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS03_S04', method_impl= MethodInstance.MethodImplementation(setS03_S04_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS18_S19', method_impl= MethodInstance.MethodImplementation(setS18_S19_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS21', method_impl= MethodInstance.MethodImplementation(setS21_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS20', method_impl= MethodInstance.MethodImplementation(setS20_body()), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setS22', method_impl= MethodInstance.MethodImplementation(setS22_body()), access_type=accessLevel3)

    #Slave Set Methods
    client.account.methods(compressor.id).create(name='setSlaveFwVersion_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveFwVersion_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveFwVersion_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveFwVersion_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveFwVersion_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveFwVersion_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveFwVersion_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveFwVersion_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerState_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveControllerState_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerState_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveControllerState_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerState_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveControllerState_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerState_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveControllerState_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveRelativeSpeed_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveRelativeSpeed_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveRelativeSpeed_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveRelativeSpeed_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveRelativeSpeed_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveRelativeSpeed_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveRelativeSpeed_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveRelativeSpeed_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerType_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveControllerType_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerType_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveControllerType_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerType_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveControllerType_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveControllerType_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveControllerType_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveSelenoidDelay_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveSelenoidDelay_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveSelenoidDelay_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveSelenoidDelay_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveSelenoidDelay_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveSelenoidDelay_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveSelenoidDelay_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveSelenoidDelay_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveAirFlow_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveAirFlow_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveAirFlow_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveAirFlow_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveAirFlow_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveAirFlow_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveAirFlow_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveAirFlow_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNominalPower_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveNominalPower_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNominalPower_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveNominalPower_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNominalPower_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveNominalPower_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNominalPower_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveNominalPower_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveUnloadPower_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveUnloadPower_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveUnloadPower_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveUnloadPower_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveUnloadPower_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveUnloadPower_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveUnloadPower_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveUnloadPower_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS0_Comp0', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS0_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS0_Comp1', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS0_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS0_Comp2', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS0_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS0_Comp3', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS0_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS1_Comp0', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS1_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS1_Comp1', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS1_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS1_Comp2', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS1_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS1_Comp3', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS1_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS2_Comp0', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS2_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS2_Comp1', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS2_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS2_Comp2', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS2_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS2_Comp3', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS2_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS3_Comp0', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS3_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS3_Comp1', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS3_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS3_Comp2', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS3_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlavePriorityInS3_Comp3', method_impl= MethodInstance.MethodImplementation(setSlavePriorityInS3_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setC00x', method_impl= MethodInstance.MethodImplementation(setC0Xx_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setC01x', method_impl= MethodInstance.MethodImplementation(setC0Xx_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setC02x', method_impl= MethodInstance.MethodImplementation(setC0Xx_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setC03x', method_impl= MethodInstance.MethodImplementation(setC0Xx_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setM00x', method_impl= MethodInstance.MethodImplementation(setM0Xx_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setM01x', method_impl= MethodInstance.MethodImplementation(setM0Xx_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setM02x', method_impl= MethodInstance.MethodImplementation(setM0Xx_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setM03x', method_impl= MethodInstance.MethodImplementation(setM0Xx_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfTotalCompressorHours_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfTotalCompressorHours_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfTotalCompressorHours_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfTotalCompressorHours_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfTotalCompressorHours_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfTotalCompressorHours_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfTotalCompressorHours_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfTotalCompressorHours_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfLoadCompressorHours_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfLoadCompressorHours_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfLoadCompressorHours_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfLoadCompressorHours_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfLoadCompressorHours_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfLoadCompressorHours_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveNumberOfLoadCompressorHours_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveNumberOfLoadCompressorHours_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveMaintCounters_Comp0', method_impl= MethodInstance.MethodImplementation(setSlaveMaintCounters_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveMaintCounters_Comp1', method_impl= MethodInstance.MethodImplementation(setSlaveMaintCounters_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveMaintCounters_Comp2', method_impl= MethodInstance.MethodImplementation(setSlaveMaintCounters_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setSlaveMaintCounters_Comp3', method_impl= MethodInstance.MethodImplementation(setSlaveMaintCounters_body(3)), access_type=accessLevel3)
    # Clock Timers
    client.account.methods(compressor.id).create(name='setClockTimer0', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(0)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer1', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(1)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer2', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(2)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer3', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(3)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer4', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(4)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer5', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(5)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer6', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(6)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer7', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(7)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer8', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(8)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer9', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(9)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer10', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(10)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer11', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(11)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer12', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(12)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer13', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(13)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer14', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(14)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer15', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(15)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer16', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(16)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer17', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(17)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer18', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(18)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer19', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(19)), access_type=accessLevel3)
    client.account.methods(compressor.id).create(name='setClockTimer20', method_impl= MethodInstance.MethodImplementation(setClockTimer_body(20)), access_type=accessLevel3)

    accessLevel4 = 'public'

    # Controller specific tag R/W operations - Read-only tags first
    client.account.methods(compressor.id).create(name='readAmbientTemperature', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('AmbientTemperature')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readInternalVoltageVcc', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('InternalVoltageVcc')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readInternalVoltageVL', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('InternalVoltageVL')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readResidualCompressorCapacity', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('ResidualCompressorCapacity')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readExcessCompressorCapacity', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('ExcessCompressorCapacity')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCurrentStopPressure', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CurrentStopPressure')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCurrentStartPressure', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CurrentStartPressure')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCurrentTotalPower', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CurrentTotalPower')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readAverageAirDelivery', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('AverageAirDelivery')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCurrentTotalAirDelivery', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CurrentTotalAirDelivery')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsConfigured', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsConfigured')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsSlave', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsSlave')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsSetToMaintenance', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsSetToMaintenance')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsAvailable', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsAvailable')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsSelected', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsSelected')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readCompressorsOn', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('CompressorsOn')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readIOBoardFwVersion', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('IOBoardFwVersion')), access_type=accessLevel4)

    client.account.methods(compressor.id).create(name='readTotalEnergyConsumption', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('TotalEnergyConsumption')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readAirProduced', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('AirProduced')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readWPx', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('WP')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readWTx', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('WT')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readR02', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('R02')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readV01', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('V01')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readV04', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('V04')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readV02_V03', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('V02')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readV07', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('V07')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS11', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S11')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readT01', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('T01')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS14', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('RS14')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readR01', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('R01')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS00_S01_S02', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S00')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS09_S10', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S09')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS06', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S06')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS05', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S05')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS07', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S07')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS12_S13', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S12')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS17', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S17')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS16', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S16')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS03_S04', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S03')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS18_S19', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S18')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS21', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S21')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS20', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S20')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readS22', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('S22')), access_type=accessLevel4)

    client.account.methods(compressor.id).create(name='readSlaveFwVersions', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveFwVersion')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveControllerStates', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveControllerState')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveRelativeSpeeds', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveRelativeSpeed')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveControllerTypes', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveControllerType')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveSelenoidDelays', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveSelenoidDelay')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveAirFlows', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveAirFlow')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveNominalPowers', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveNominalPower')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveUnloadPowers', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveUnloadPower')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlavePriorityInS0s', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlavePriorityInS0')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlavePriorityInS1s', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlavePriorityInS1')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlavePriorityInS2s', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlavePriorityInS2')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlavePriorityInS3s', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlavePriorityInS3')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readC0xs', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('C0x')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readM0xs', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('M0x')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveNumberOfTotalCompressorHours', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveNumberOfTotalCompressorHours')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveNumberOfLoadCompressorHours', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveNumberOfLoadCompressorHours')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readSlaveMaintCounters', method_impl= MethodInstance.MethodImplementation(readSlaveTagIntoProperty_body('SlaveMaintCounters')), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='readClockTimers', method_impl= MethodInstance.MethodImplementation(readClockTimerIntoProperty_body('ClockTimer')), access_type=accessLevel4)

    client.account.methods(compressor.id).create(name='writeTotalEnergyConsumption', method_impl= MethodInstance.MethodImplementation(writeTotalEnergyConsumption_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeAirProduced', method_impl= MethodInstance.MethodImplementation(writeAirProduced_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeWTx', method_impl= MethodInstance.MethodImplementation(writeWTx_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeWPx', method_impl= MethodInstance.MethodImplementation(writeWPx_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeR02', method_impl= MethodInstance.MethodImplementation(writeR02_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeV01', method_impl= MethodInstance.MethodImplementation(writeV01_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeV04', method_impl= MethodInstance.MethodImplementation(writeV04_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeV02_V03', method_impl= MethodInstance.MethodImplementation(writeV02_V03_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeV07', method_impl= MethodInstance.MethodImplementation(writeV07_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS11', method_impl= MethodInstance.MethodImplementation(writeS11_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeT01', method_impl= MethodInstance.MethodImplementation(writeT01_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS14', method_impl= MethodInstance.MethodImplementation(writeS14_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeR01', method_impl= MethodInstance.MethodImplementation(writeR01_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS00_S01_S02', method_impl= MethodInstance.MethodImplementation(writeS00_S01_S02_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS09_S10', method_impl= MethodInstance.MethodImplementation(writeS09_S10_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS06', method_impl= MethodInstance.MethodImplementation(writeS06_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS05', method_impl= MethodInstance.MethodImplementation(writeS05_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS07_S08', method_impl= MethodInstance.MethodImplementation(writeS07_S08_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS12_S13', method_impl= MethodInstance.MethodImplementation(writeS12_S13_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS17', method_impl= MethodInstance.MethodImplementation(writeS17_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS16', method_impl= MethodInstance.MethodImplementation(writeS16_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS03_S04', method_impl= MethodInstance.MethodImplementation(writeS03_S04_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS18_S19', method_impl= MethodInstance.MethodImplementation(writeS18_S19_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS21', method_impl= MethodInstance.MethodImplementation(writeS21_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS20', method_impl= MethodInstance.MethodImplementation(writeS20_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeS22', method_impl= MethodInstance.MethodImplementation(writeS22_body()), access_type=accessLevel4)

    client.account.methods(compressor.id).create(name='writeSlaveControllerTypes', method_impl= MethodInstance.MethodImplementation(writeSlaveControllerType_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveSelenoidDelays', method_impl= MethodInstance.MethodImplementation(writeSlaveSelenoidDelay_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveAirFlows', method_impl= MethodInstance.MethodImplementation(writeSlaveAirFlow_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveNominalPowers', method_impl= MethodInstance.MethodImplementation(writeSlaveNominalPower_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveUnloadPowers', method_impl= MethodInstance.MethodImplementation(writeSlaveUnloadPower_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlavePriorityInS0s', method_impl= MethodInstance.MethodImplementation(writeSlavePriorityInS0_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlavePriorityInS1s', method_impl= MethodInstance.MethodImplementation(writeSlavePriorityInS1_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlavePriorityInS2s', method_impl= MethodInstance.MethodImplementation(writeSlavePriorityInS2_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlavePriorityInS3s', method_impl= MethodInstance.MethodImplementation(writeSlavePriorityInS3_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeC0xs', method_impl= MethodInstance.MethodImplementation(writeC0Xx_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeM0xs', method_impl= MethodInstance.MethodImplementation(writeM0Xx_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveNumberOfTotalCompressorHours', method_impl= MethodInstance.MethodImplementation(writeSlaveNumberOfTotalCompressorHours_body()), access_type=accessLevel4)
    client.account.methods(compressor.id).create(name='writeSlaveNumberOfLoadCompressorHours', method_impl= MethodInstance.MethodImplementation(writeSlaveNumberOfLoadCompressorHours_body()), access_type=accessLevel4)
   
    #Base Methods
    accessLevel1_1 = 'private'
    accessLevel1 = 'protected'
    client.account.methods(compressor.id).create(name='setAlarms', method_impl= MethodInstance.MethodImplementation(setAlarms_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setNonAckAlarms', method_impl= MethodInstance.MethodImplementation(setNonAckAlarms_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setControllerState', method_impl= MethodInstance.MethodImplementation(setControllerState_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setBlockingAlarm', method_impl= MethodInstance.MethodImplementation(setBlockingAlarm_body()), access_type=accessLevel1_1)

    client.account.methods(compressor.id).create(name='setLevel1Pwd', method_impl= MethodInstance.MethodImplementation(setLevelXPwd_body(1)), access_type=accessLevel1_1)

    client.account.methods(compressor.id).create(name='calculateAll', method_impl= MethodInstance.MethodImplementation(calculateAll_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='convertToHours', method_impl= MethodInstance.MethodImplementation(convertToHours_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='convertToDec', method_impl= MethodInstance.MethodImplementation(convertToDec_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setAny', method_impl= MethodInstance.MethodImplementation(setAny_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setSerialNumber', method_impl= MethodInstance.MethodImplementation(setSerialNumber_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setLogikaModel', method_impl= MethodInstance.MethodImplementation(setLogikaModel_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setLogikaFwVersion', method_impl= MethodInstance.MethodImplementation(setLogikaFwVersion_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='setAlarms', method_impl= MethodInstance.MethodImplementation(setAlarms_body()), access_type=accessLevel1_1)
    client.account.methods(compressor.id).create(name='writeAnyTag', method_impl= MethodInstance.MethodImplementation(writeAnyTag_body()), access_type=accessLevel2, description="""
    Bu method ile herhangi bir tag'i yazabilirsiniz. Gereken parametreler sunlar:

    - setValue: Yazilacak deger
    - addr: Tag'in modbus adresi
    - size: Yazilacak tag'in uzunlugu - default 2 (word)

    Ornegin:

    { "setValue": 13, "addr": "0x401", "size": 2 } 
    """)
    client.account.methods(compressor.id).create(name='readAnyTag', method_impl= MethodInstance.MethodImplementation(readAnyTag_body()), access_type=accessLevel2, description="""
    Bu method ile herhangi bir tag'i okumak icin gateway'e komut gonderebilirsiniz. Okunan deger tagValue isimli property icine yailir. 
    Gereken parametreler sunlar:

    - addr: Tag'in modbus adresi
    - size: Okunacak tag'in uzunlugu - default 2 (word)

    Ornegin:

    { "addr": "0x401", "size": 2 } 
    """)
    client.account.methods(compressor.id).create(name='readSerialNumber', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('cfgSerialNumber')), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='readLogikaModel', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('cfgLogikaModel')), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='readLogikaFwVersion', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('cfgLogikaFwVersion')), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='readLevel1Pwd', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('cfgLevel1Pwd')), access_type=accessLevel2)
    client.account.methods(compressor.id).create(name='readControllerTime', method_impl= MethodInstance.MethodImplementation(readTagIntoProperty_body('controllerTime')), access_type=accessLevel2)